spring.application.name=shareit-ziyat

logging.level.com.practice.shareitziyat=debug

spring.datasource.url=jdbc:postgresql://postgres-db/shareit
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.sql.init.mode=always

server.port=9090